[project]
name = "topic-intelligence-copliot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.104.0",
    "fastapi>=0.136.1",
    "openai>=2.38.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "rich>=15.0.0",
    "typer>=0.25.1",
    "typing>=3.10.0.0",
]
[project.scripts]
fde = "topic_agent.cli:app"

[tool.uv]
package = true
