from topic_agent.models import TrustedSource


TRUSTED_SOURCES = [
    TrustedSource(
        name="OpenAI News",
        domain="openai.com",
        search_scope="site:openai.com/news",
        source_type="official_ai_lab",
        topics=["AI agents", "LLMs", "tool use", "OpenAI", "agentic AI"],
    ),
    TrustedSource(
        name="Anthropic News",
        domain="anthropic.com",
        search_scope="site:anthropic.com/news",
        source_type="official_ai_lab",
        topics=["AI agents", "Claude", "tool use", "computer use", "agentic AI"],
    ),
    TrustedSource(
        name="Google DeepMind Blog",
        domain="deepmind.google",
        search_scope="site:deepmind.google/discover/blog",
        source_type="official_ai_lab",
        topics=["AI agents", "LLMs", "Gemini", "reinforcement learning", "AI research"],
    ),
    TrustedSource(
        name="Google AI Blog",
        domain="blog.google",
        search_scope="site:blog.google/technology/ai",
        source_type="official_ai_lab",
        topics=["AI agents", "Gemini", "Google AI", "LLMs", "AI products"],
    ),
    TrustedSource(
        name="Meta AI Blog",
        domain="ai.meta.com",
        search_scope="site:ai.meta.com/blog",
        source_type="official_ai_lab",
        topics=["AI agents", "LLMs", "Llama", "open models", "AI research"],
    ),
    TrustedSource(
        name="Microsoft AI Blog",
        domain="blogs.microsoft.com",
        search_scope="site:blogs.microsoft.com/ai",
        source_type="official_ai_lab",
        topics=["AI agents", "Copilot", "enterprise AI", "Microsoft AI", "agentic AI"],
    ),
    TrustedSource(
        name="Microsoft Research Blog",
        domain="microsoft.com",
        search_scope="site:microsoft.com/en-us/research/blog",
        source_type="research_lab_blog",
        topics=["AI agents", "LLMs", "AI research", "multi-agent systems", "evaluation"],
    ),
    TrustedSource(
        name="Mistral AI News",
        domain="mistral.ai",
        search_scope="site:mistral.ai/news",
        source_type="official_ai_lab",
        topics=["AI agents", "LLMs", "open models", "Mistral", "AI infrastructure"],
    ),
    TrustedSource(
        name="Cohere Blog",
        domain="cohere.com",
        search_scope="site:cohere.com/blog",
        source_type="official_ai_lab",
        topics=["AI agents", "enterprise AI", "RAG", "LLMs", "tool use"],
    ),

    TrustedSource(
        name="LangChain Blog",
        domain="blog.langchain.com",
        search_scope="site:blog.langchain.com",
        source_type="framework_blog",
        topics=["AI agents", "LangGraph", "agent frameworks", "orchestration", "tool use"],
    ),
    TrustedSource(
        name="LangGraph Documentation",
        domain="langchain-ai.github.io",
        search_scope="site:langchain-ai.github.io/langgraph",
        source_type="developer_docs",
        topics=["AI agents", "LangGraph", "agent orchestration", "stateful agents", "workflows"],
    ),
    TrustedSource(
        name="LlamaIndex Blog",
        domain="llamaindex.ai",
        search_scope="site:llamaindex.ai/blog",
        source_type="framework_blog",
        topics=["AI agents", "RAG", "agent frameworks", "LlamaIndex", "knowledge agents"],
    ),
    TrustedSource(
        name="LlamaIndex Documentation",
        domain="docs.llamaindex.ai",
        search_scope="site:docs.llamaindex.ai",
        source_type="developer_docs",
        topics=["AI agents", "RAG", "agent workflows", "data agents", "LlamaIndex"],
    ),
    TrustedSource(
        name="Hugging Face Blog",
        domain="huggingface.co",
        search_scope="site:huggingface.co/blog",
        source_type="technical_blog",
        topics=["AI agents", "LLMs", "open models", "transformers", "AI tooling"],
    ),
    TrustedSource(
        name="Weights & Biases Blog",
        domain="wandb.ai",
        search_scope="site:wandb.ai/blog",
        source_type="technical_blog",
        topics=["AI agents", "LLM evaluation", "AI observability", "experiments", "model monitoring"],
    ),
    TrustedSource(
        name="Composio Blog",
        domain="composio.dev",
        search_scope="site:composio.dev/blog",
        source_type="framework_blog",
        topics=["AI agents", "tool use", "agent tools", "integrations", "agentic workflows"],
    ),
    TrustedSource(
        name="CrewAI Blog",
        domain="crewai.com",
        search_scope="site:crewai.com/blog",
        source_type="framework_blog",
        topics=["AI agents", "multi-agent systems", "CrewAI", "agent frameworks", "workflows"],
    ),
    TrustedSource(
        name="AutoGen Documentation",
        domain="microsoft.github.io",
        search_scope="site:microsoft.github.io/autogen",
        source_type="developer_docs",
        topics=["AI agents", "multi-agent systems", "AutoGen", "agent frameworks", "Microsoft"],
    ),
    TrustedSource(
        name="Semantic Kernel Blog",
        domain="devblogs.microsoft.com",
        search_scope="site:devblogs.microsoft.com/semantic-kernel",
        source_type="framework_blog",
        topics=["AI agents", "Semantic Kernel", "enterprise agents", "Microsoft", "orchestration"],
    ),

    TrustedSource(
        name="arXiv",
        domain="arxiv.org",
        search_scope="site:arxiv.org",
        source_type="academic_research",
        topics=["AI agents", "LLMs", "multi-agent systems", "agent evaluation", "AI research"],
    ),
    TrustedSource(
        name="Papers with Code",
        domain="paperswithcode.com",
        search_scope="site:paperswithcode.com",
        source_type="research_index",
        topics=["AI agents", "benchmarks", "LLMs", "evaluation", "machine learning papers"],
    ),
    TrustedSource(
        name="ACL Anthology",
        domain="aclanthology.org",
        search_scope="site:aclanthology.org",
        source_type="academic_research",
        topics=["AI agents", "LLMs", "NLP", "language models", "tool use"],
    ),
    TrustedSource(
        name="Google Scholar",
        domain="scholar.google.com",
        search_scope="site:scholar.google.com",
        source_type="research_index",
        topics=["AI agents", "LLMs", "academic papers", "research", "citations"],
    ),

    TrustedSource(
        name="AWS Machine Learning Blog",
        domain="aws.amazon.com",
        search_scope="site:aws.amazon.com/blogs/machine-learning",
        source_type="cloud_ai_blog",
        topics=["AI agents", "Bedrock", "enterprise AI", "cloud AI", "agentic workflows"],
    ),
    TrustedSource(
        name="Google Cloud AI Blog",
        domain="cloud.google.com",
        search_scope="site:cloud.google.com/blog/products/ai-machine-learning",
        source_type="cloud_ai_blog",
        topics=["AI agents", "Vertex AI", "Gemini", "enterprise AI", "cloud AI"],
    ),
    TrustedSource(
        name="Azure AI Blog",
        domain="azure.microsoft.com",
        search_scope="site:azure.microsoft.com/en-us/blog/topics/ai-machine-learning",
        source_type="cloud_ai_blog",
        topics=["AI agents", "Azure AI", "Copilot", "enterprise AI", "cloud AI"],
    ),
    TrustedSource(
        name="Databricks Blog",
        domain="databricks.com",
        search_scope="site:databricks.com/blog",
        source_type="data_ai_blog",
        topics=["AI agents", "data intelligence", "enterprise AI", "MLOps", "RAG"],
    ),
    TrustedSource(
        name="Snowflake Blog",
        domain="snowflake.com",
        search_scope="site:snowflake.com/blog",
        source_type="data_ai_blog",
        topics=["AI agents", "enterprise AI", "data apps", "RAG", "AI infrastructure"],
    ),

    TrustedSource(
        name="Chip Huyen Blog",
        domain="huyenchip.com",
        search_scope="site:huyenchip.com",
        source_type="independent_technical_blog",
        topics=["AI agents", "LLM systems", "AI engineering", "machine learning systems", "evaluation"],
    ),
    TrustedSource(
        name="Simon Willison Blog",
        domain="simonwillison.net",
        search_scope="site:simonwillison.net",
        source_type="independent_technical_blog",
        topics=["AI agents", "LLMs", "tool use", "AI engineering", "developer tools"],
    ),
    TrustedSource(
        name="Latent Space",
        domain="latent.space",
        search_scope="site:latent.space",
        source_type="technical_newsletter",
        topics=["AI agents", "LLMs", "AI engineering", "AI startups", "developer tools"],
    ),
    TrustedSource(
        name="The Batch",
        domain="deeplearning.ai",
        search_scope="site:deeplearning.ai/the-batch",
        source_type="ai_newsletter",
        topics=["AI agents", "AI research", "LLMs", "AI industry", "machine learning"],
    ),
    TrustedSource(
        name="Import AI",
        domain="importai.substack.com",
        search_scope="site:importai.substack.com",
        source_type="ai_newsletter",
        topics=["AI agents", "AI policy", "AI research", "frontier AI", "AI safety"],
    ),
]